### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by Andy16k** [Nur1Labs/CryptonoteEvo-CLI#1]
For issue need

1. Post title bug
2. Post the code error[used code tag please]
3. Send Screenshot
4. if too long please used pastebin

Example

"bug on build"

this bug like this code :
[put code]

this additional screenshot :
[upload picture]

hmmm too long code i will give pastebin url :
[this url paste bin]

## [  ] Kohaku Team Developer && Cryptonote Family

hi

tried running make but it says  - make: *** No targets specified and no makefile found. Stop.

**Comment by FndNur1Labs** [comment]
you need this

`mkdir build && cd build && cmake -DUSE_SSL=0 ..`

then you can

`make`

**Comment by Andy16k** [comment]
Cool, I'll give it a try
Thankyou



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
