### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by xaria-coin** [Nur1Labs/CryptonoteEvo-CLI#2]
[ 71%] Building CXX object CMakeFiles/tests.dir/src/main_tests.cpp.o
In file included from /home/andy/CryptonoteEvo-CLI/src/platform/DB.hpp:9:0,
                 from /home/andy/CryptonoteEvo-CLI/src/Core/BlockChain.hpp:6,
                 from /home/andy/CryptonoteEvo-CLI/src/Core/BlockChainState.hpp:9,
                 from /home/andy/CryptonoteEvo-CLI/src/main_tests.cpp:2:
/home/andy/CryptonoteEvo-CLI/src/platform/DBlmdb.hpp:3:10: fatal error: lmdb.h: No such file or directory
 #include <lmdb.h>
          ^~~~~~~~
compilation terminated.
CMakeFiles/tests.dir/build.make:62: recipe for target 'CMakeFiles/tests.dir/src/main_tests.cpp.o' failed
make[2]: *** [CMakeFiles/tests.dir/src/main_tests.cpp.o] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/tests.dir/all' failed
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Shiro20** [comment]
https://github.com/FndNur1Labs/CryptonoteEvo/wiki/Installation-Base-From-Myself%5BFndNur1Labs%5D

**Comment by FndNur1Labs** [comment]
you need git clone lmdb. follow up guide by @Shiro20
