### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Andy16k** [Nur1Labs/CryptonoteEvo-CLI#5]
tried following your guide, have dowlnoaded all libraries etc etc, but it failed again - 

andy@andy-VirtualBox:~/CryptonoteEvo-CLI/build$ make -j4 evonote-crypto
[  4%] Building C object CMakeFiles/evonote-crypto.dir/src/crypto/tree-hash.c.o
/home/andy/CryptonoteEvo-CLI/src/crypto/tree-hash.c:12:10: fatal error: crypto-cuckoo_load.h: No such file or directory
 #include "crypto-cuckoo_load.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/evonote-crypto.dir/build.make:518: recipe for target 'CMakeFiles/evonote-crypto.dir/src/crypto/tree-hash.c.o' failed
make[3]: *** [CMakeFiles/evonote-crypto.dir/src/crypto/tree-hash.c.o] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/evonote-crypto.dir/all' failed
make[2]: *** [CMakeFiles/evonote-crypto.dir/all] Error 2
CMakeFiles/Makefile2:154: recipe for target 'CMakeFiles/evonote-crypto.dir/rule' failed
make[1]: *** [CMakeFiles/evonote-crypto.dir/rule] Error 2
Makefile:144: recipe for target 'evonote-crypto' failed
make: *** [evonote-crypto] Error 2

**Comment by FndNur1Labs** [comment]
Fixed #6
