### ISSUE TITLE
Genesis block failed to add

### ISSUE THREAD

**Issue by hifromjarrod** [nur1labs/CryptonoteEvo-CLI#9]
When I run ./cryptonoted I get the following error:

`Starting multicore ring checker using 2/4 cpus`

`Exception in main() - Genesis block failed to add`

`libc++abi.dylib: terminating with uncaught exception of type std::logic_error: Genesis block failed to add`

`[1]    35873 abort      ./jormocoind`

If anyone could help I would really appreciate it.

**Comment by Shiro20** [comment]
not solving yet
